name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
      with:
        php_version: "8.3"
    - uses: php-actions/phpunit@v7
      with:
        version: 9.6
        php_extensions: xdebug
        php_version: 8.3
        bootstrap: vendor/autoload.php
        configuration: test/phpunit.xml
        args: --coverage-text
      env:
        XDEBUG_MODE: coverage
        TEST_NAME: Hipcall SDK